language: scala
scala: 2.10.5
jdk: oraclejdk8
script:
  - sbt ++$TRAVIS_SCALA_VERSION scripted
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete
